sudo: required
services:
  - docker

before_install:
  - docker build -t karanc10/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karanc10/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-624417255488"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"